source "sso://user/paulbeusterien/Specs"
source "https://github.com/CocoaPods/Specs.git"

use_frameworks!

target 'MyLibrary_Example' do
  pod 'MyLibrary', :path => '../'
    pod 'MyLibrary3', :path => '../'

  target 'MyLibrary_Tests' do
    inherit! :search_paths

#pod 'Specta'
    # pod 'Expecta'
  end
end


#pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    #  def installer.verify_no_static_framework_transitive_dependencies; end
    #end
